var modelUrl = 'http://w3id.org/cdif/ddsc/1.0/ddsc/xmi/';
var modelDocumentationUrl = '';
var definition = {
	"Classes": "This package contains the definitions of the classes in the DDSC profile with all their relationships and attributes.",
	"DDSC": "Profile for Data Description",
	"DataTypes": "",
	"Enumerations": "",
	"StructuredDataTypes": "",
	"XMLSchemaDataTypes": "",
	"AttributeComponent": "Role given to a represented variable in the context of a data structure to qualify observations or provide other types of supplementary information.",
	"ComponentPosition": "Indexes the components in a data structure using integers with a position indicated by incrementing upward from 0 or 1.",
	"DataStore": "Collection of logical records.",
	"Descriptor": "Use of a code for variable identification in the context of a data structure and a variable descriptor component.",
	"DescriptorValueDomain": "Set of permissible values for a variable playing the role of a variable descriptor component.",
	"DescriptorVariable": "Variable that provides codes for variable identification in the context of a data structure. Variable playing the role of a variable descriptor component.",
	"DimensionComponent": "Role given to a represented variable in the context of a dimensional data structure to identify the universes associated with data points. The variable acts as a field in the compound identifier (the key structure) to disambiguate the cells in the multi-dimensional \"cube\".",
	"DimensionalDataSet": "Organized collection of multidimensional data. It is structured by a dimensional data structure.",
	"DimensionalDataStructure": "Structure of a dimensional data set (organized collection of multidimensional data). It is described by dimension, measure and attribute components.",
	"IdentifierComponent": "Role given to a represented variable in the context of a long or wide data structure to identify the units associated to data points, and in dimensional and key value data structures to provide identifying fields for the instance values.",
	"InstanceVariable": "Use of a represented variable within a data set.",
	"LogicalRecord": "Collection of instance variables.",
	"LongDataSet": "Organized collection of long data. It is structured by a long data structure.",
	"LongDataStructure": "Structure of a long dataset (organized collection of long data). It is described by identifier, measure, attribute, variable descriptor and variable value components.",
	"MeasureComponent": "Role given to a represented variable in the context of a data structure to hold the observed/derived values.",
	"PhysicalSegmentLayout": "Used as an extension point in the description of the different layout styles of data structure descriptions.",
	"Population": "Universe with time and geography specified.",
	"PrimaryKey": "Role of a set of data structure components for content linkage purposes",
	"PrimaryKeyComponent": "Role of a data structure component for content identification purposes",
	"ReferenceVariable": "Variable that records values of multiple variables in the context of a data structure. Variable playing the role of a variable value component.",
	"RepresentedVariable": "Conceptual variable with a substantive value domain specified.",
	"SentinelValueDomain": "Value domain for a sentinel conceptual domain.",
	"SubstantiveValueDomain": "Value domain for a substantive conceptual domain. Typically a description and/or enumeration of allowed values of interest.",
	"UnitType": "Unit type is a type or class of objects of interest (units).",
	"Universe": "Specialized unit type, with the specialization based upon characteristics other than time and geography.",
	"ValueMapping": "Physical characteristics for the value of an instance variable stored in a data point as part of a physical segment layout.",
	"ValueMappingPosition": "Denotes the position of a value mapping in a sequence.",
	"VariableDescriptorComponent": "Role given to a represented variable in the context of a data structure to provide codes for variable identification.",
	"VariableValueComponent": "Role given to a represented variable in the context of a data structure to record values of multiple variables.",
	"WideDataSet": "Organized collection of wide data. It is structured by a wide data structure.",
	"WideDataStructure": "Structure of a wide dataset (organized collection of wide data). It is described by identifier, measure and attribute components.",
	"BibliographicName": "Personal names should be listed surname or family name first, followed by forename or given name. When in doubt, give the name as it appears, and do not invert. In the case of organizations where there is clearly a hierarchy present, list the parts of the hierarchy from largest to smallest, separate ...",
	"CombinedDate": "Provides the structure of a single Date expressed in an ISO date structure along with equivalent expression in any number of non-ISO formats. While it supports the use of the ISO time interval structure this should only be used when the exact date is unclear (i.e. occurring at some point in time bet ...",
	"ControlledVocabularyEntry": "Allows for unstructured content which may be an entry from an externally maintained controlled vocabulary.If the content is from a controlled vocabulary provide the code value of the entry, as well as a reference to the controlled vocabulary from which the value is taken. Provide as many of the iden ...",
	"DateRange": "Expresses a date/time range using a start date and end date (both with the structure of Date and supporting the use of ISO and non-ISO date structures). Use in all locations where a range of dates is required, i.e. validFor, embargoPeriod, collectionPeriod, etc.",
	"InternationalRegistrationDataIdentifier": "Persistent, globally unique object identifier aligned with ISO/IEC 11179-6:2015, Information technology - Metadata registries (MDR) - Part 6: Registration, Annex A, Identifiers based on ISO/IEC 6523, http://standards.iso.org/ittf/PubliclyAvailableStandards/c060342_ISO_IEC_11179-6_2015.zip. The uniqu ...",
	"InternationalString": "Packaging structure for multilingual versions of the same string content, represented by a set of LanguageString. Only one LanguageString per language/scope type is allowed. Where an element of this type (InternationalString) is repeatable, the expectation is that each repetition contains a differen ...",
	"LabelForDisplay": "A structured display label. Label provides display content of a fully human readable display for the identification of the object.",
	"LanguageString": "A data type which describes a string specific to a language/scope combination. It contains the following attributes: language to designate the language, isTranslated with a default value of false to designate if an object is a translation of another language, isTranslatable with a default value of t ...",
	"ModelIdentification": "Attributes for the model identification with constant values.",
	"NonDdiIdentifier": "A unique set of attributes, not conforming to the DDI identifier structure nor structured as a URI, used to identify some entity.",
	"NonIsoDate": "Used to preserve an historical date, formatted in a non-ISO fashion.",
	"ObjectAttributeSelector": "A resource which describes a specific attribute of an object. It is defined in the style of selectors of the Web Annotation Vocabulary, see https://www.w3.org/TR/annotation-vocab/. The selector can be nested dependent on the structure of the referenced object.",
	"ObjectName": "A standard means of expressing a name for a class object. A linguistic signifier. Human understandable name (word, phrase, or mnemonic) that reflects the ISO/IEC 11179-5 naming principles.",
	"OrganizationName": "Names by which the organization is known. Use the attribute isFormal with a value of True to designate the legal or formal name of the organization. Names may be typed with typeOfOrganizationName to indicate their appropriate usage.",
	"Reference": "Provides a way of pointing to resources outside of the information described in the set of DDI-CDI metadata.",
	"Selector": "A resource which describes the segment of interest in a representation of a resource. This class is not used directly, only its subclasses. It is defined accordingly the related selector of the Web Annotation Vocabulary, see https://www.w3.org/TR/annotation-vocab/#selector.",
	"TextPositionSelector": "Describes a range of text by recording the start and end positions of the selection in the object. Position 0 would be immediately before the first character, position 1 would be immediately before the second character, and so on. It is defined accordingly the related selector of the Web Annotation ...",
	"TrimValues": "Specifies which spaces to remove from a data value (start, end, both, neither).",
	"TypedString": "TypedString combines a type with content defined as a simple string. May be used wherever a simple string needs to support a type definition to clarify its content.",
	"XsdAnyUri": "Primitive data type \"anyURI\" of the XML Schema data types. Definition from XML Schema Part 2: Datatypes Second Edition: \"anyURI\" represents a Uniform Resource Identifier Reference (URI). An \"anyURI\" value can be absolute or relative, and may have an optional fragment identifier (i.e., it may be a UR ...",
	"XsdDate": "Primitive data type \"date\" of the XML Schema data types. Definition from XML Schema Part 2: Datatypes Second Edition: \"The value space of date consists of top-open intervals of exactly one day in length on the timelines of dateTime, beginning on the beginning moment of each day (in each timezone), i ...",
	"XsdLanguage": "Derived data type \"language\" of the XML Schema data types. Definition from XML Schema Part 2: Datatypes Second Edition: \"language\" represents natural language identifiers as defined by by [RFC 3066]. The value space of \"language\" is the set of all strings that are valid language identifiers as defin ...",
	"tooltip.aggregation-kind": "A shared aggregation is a variant of the association relationship; aggregation is more specific than association. It is an association that represents a part-whole or part-of relationship. The composite aggregation relationship is a stronger form of aggregation where the aggregate controls the lifecycle of the elements it aggregates.",
	"tooltip.association": "An association is a relationship between classes which is used to show that instances of classes could be linked to each other.",
	"tooltip.attribute": "Attributes (of a class or data type) hold data that is relevant to the entire class, not just a single object. For example, in a Car class, the number of wheels (assuming all cars have the same number) could be a class attribute.",
	"tooltip.canonical-xmi": "Canonical XMI constitutes a specific constrained format of XMI that supports interoperability between UML tools.",
	"tooltip.class": "A class classifies a set of objects and specifies the features that characterize the structure and behavior of those objects.",
	"tooltip.classifier": "Class or data type. ",
	"tooltip.coupling": "Coupling is the degree of interdependence between packages.",
	"tooltip.data-type": "Data types represent value types from primitive types like string or structured data types (other data types).",
	"tooltip.diagram": "A UML class diagram visually represents the structure of the class, including its attributes and their data types, as well as its relationships to other classes. ",
	"tooltip.enumeration": "An enumeration is a data type whose values are enumerated as defined enumeration literals.",
	"tooltip.encoding": "A target language refers to the programming language or platform for which the UML model is intended to be used to generate code.",
	"tooltip.enumeration-literal": "Enumeration literals are elements that represent named values in an enumeration.",
	"tooltip.inheritance": "The generalization relationship - also known as the inheritance relationship - captures the idea of one class, the so-called subclass, being a specialized form of the other (the superclass, super type, or base class). Where this relationship holds, the superclass is considered a generalization of the subclass. ",
	"tooltip.json-schema": "JSON Schema is the vocabulary that enables JSON data consistency, validity, and interoperability at scale.",
	"tooltip.json-ld": "JSON-LD is a method of encoding linked data using JSON and of serializing data similarly to traditional JSON.",
	"tooltip.multiplicity": "Multiplicity is a definition of cardinality - i.e. number of elements - of some collection of elements by providing an inclusive interval of non-negative integers to specify the allowable number of instances of described element. Multiplicity interval has some lower bound and (possibly infinite) upper bound.",
	"tooltip.navigability": "An end property of association is navigable from the opposite end(s) of association if instances of the classifier at this end of the link can be accessed efficiently at runtime from instances at the other ends of the link. The UML specification does not dictate how efficient this access should be or any specific mechanism to achieve the efficiency. It is implementation specific.",
	"tooltip.rdf-ontology": "RDF ontology is a formal representation of knowledge using the Resource Description Framework (RDF) that describes the concepts, relationships, and properties.",
	"tooltip.shacl": "Shapes Constraint Language (SHACL) is a language for describing Resource Description Framework (RDF) graphs. SHACL has been designed to enhance the semantic and technical interoperability layers of ontologies expressed as RDF graphs.",
	"tooltip.shex": "Shape Expressions (ShEx) is a data modelling language for validating and describing a Resource Description Framework (RDF).",
	"tooltip.usage": "Usage by a class or data type.",
	"tooltip.xml-schema": "XML Schema Definition specifies how to formally describe the elements in an Extensible Markup Language (XML) document.",
}
